# Generated by Django 6.1 on 2026-08-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "LinkedIn"),
                            ("INDEED", "Indeed"),
                            ("GLASSDOOR", "Glassdoor"),
                            ("MONSTER", "Monster"),
                            ("OTHER", "Other"),
                        ],
                        max_length=70,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("company", models.CharField(max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("salary", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("FREELANCE", "Freelance"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        default="FULL_TIME",
                        max_length=100,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level"),
                            ("MID", "Mid Level"),
                            ("SENIOR", "Senior Level"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        default="MID",
                        max_length=100,
                    ),
                ),
                ("is_remote", models.BooleanField(default=False)),
                ("is_hybrid", models.BooleanField(default=False)),
                ("source_url", models.URLField()),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("posted_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_hash",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.jobsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="UserJobPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        default=list, help_text="List of preferred locations"
                    ),
                ),
                ("remote_only", models.BooleanField(default=False)),
                ("hybrid_allowed", models.BooleanField(default=True)),
                (
                    "preferred_job_types",
                    models.JSONField(
                        default=list, help_text="List of preferred job types"
                    ),
                ),
                (
                    "preferred_experience_levels",
                    models.JSONField(
                        default=list, help_text="List of preferred experience levels"
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "include_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords that must be in job description",
                    ),
                ),
                (
                    "exclude_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords that must not be in job description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, help_text="0-100 score"),
                ),
                ("location_match", models.BooleanField(default=False)),
                ("remote_match", models.BooleanField(default=False)),
                ("salary_match", models.BooleanField(default=False)),
                (
                    "skill_match",
                    models.FloatField(
                        default=0.0, help_text="Percentage of skills matched"
                    ),
                ),
                ("experience_match", models.BooleanField(default=False)),
                ("job_type_match", models.BooleanField(default=False)),
                ("is_recommended", models.BooleanField(default=False)),
                ("evaluation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score"],
                "unique_together": {("job", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company", "title"], name="jobs_job_company_06c07c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["location", "is_remote"], name="jobs_job_locatio_6595cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["-posted_date"], name="jobs_job_posted__bd758d_idx"
            ),
        ),
    ]
