# Generated by Django 6.1 on 2026-08-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("LINKEDIN", "LinkedIn"),
                    ("INDEED", "Indeed"),
                    ("GLASSDOOR", "Glassdoor"),
                    ("FLEXJOBS", "FlexJobs"),
                    ("PROGRESSIVE", "Progressive"),
                    ("MONSTER", "Monster"),
                    ("OTHER", "Other"),
                ],
                max_length=70,
            ),
        ),
    ]
