# Generated by Django 6.1 on 2026-08-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_jobsource_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsource",
            name="url",
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
