# Generated by Django 6.1 on 2026-08-09 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobsource_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial Success"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("total_jobs_found", models.IntegerField(default=0)),
                ("total_jobs_saved", models.IntegerField(default=0)),
                ("total_jobs_duplicates", models.IntegerField(default=0)),
                ("total_jobs_failed", models.IntegerField(default=0)),
                ("ai_used", models.BooleanField(default=False)),
                ("ai_success", models.BooleanField(default=False)),
                ("ai_extracted_fields", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="userjobpreferences",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.JSONField(
                blank=True, default=list, help_text="List of benefits offered"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="education_required",
            field=models.CharField(
                blank=True,
                help_text="Education required (e.g., 'Bachelor's degree')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_required",
            field=models.CharField(
                blank=True,
                help_text="Years of experience required (e.g., '3+ years')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of keywords/tags extracted from the job",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="qualifications",
            field=models.JSONField(
                blank=True, default=list, help_text="List of preferred qualifications"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of job requirements (skills, experience, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of job responsibilities/duties",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of skills extracted from the job",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="work_arrangement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                    ("ON_SITE", "On-Site"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="ai_concerns",
            field=models.JSONField(
                blank=True, default=list, help_text="Concerns raised by AI"
            ),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="ai_match_score",
            field=models.FloatField(default=0.0, help_text="AI-generated match score"),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="ai_reasons",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Reasons provided by AI for the match",
            ),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="culture_fit",
            field=models.FloatField(default=0.0, help_text="Culture fit score (0-100)"),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="evaluated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userjobpreferences",
            name="preferred_skills",
            field=models.JSONField(
                blank=True, default=list, help_text="List of preferred skills"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="source_url",
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="jobsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("LINKEDIN", "LinkedIn"),
                    ("INDEED", "Indeed"),
                    ("GLASSDOOR", "Glassdoor"),
                    ("FLEXJOBS", "FlexJobs"),
                    ("PROGRESSIVE", "Progressive"),
                    ("MONSTER", "Monster"),
                    ("JOBRIGHT", "Jobright"),
                    ("GREENHOUSE", "Greenhouse"),
                    ("OTHER", "Other"),
                ],
                max_length=70,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_level"], name="jobs_job_experie_09027f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevaluation",
            index=models.Index(
                fields=["job", "user"], name="jobs_jobeva_job_id_6b57d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevaluation",
            index=models.Index(
                fields=["-relevance_score"], name="jobs_jobeva_relevan_c6d1b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevaluation",
            index=models.Index(
                fields=["is_recommended"], name="jobs_jobeva_is_reco_a04e65_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobprocessinglog",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_logs",
                to="jobs.jobsource",
            ),
        ),
        migrations.AddField(
            model_name="jobprocessinglog",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="jobprocessinglog",
            index=models.Index(fields=["status"], name="jobs_jobpro_status_e214d8_idx"),
        ),
        migrations.AddIndex(
            model_name="jobprocessinglog",
            index=models.Index(
                fields=["-started_at"], name="jobs_jobpro_started_ddbd94_idx"
            ),
        ),
    ]
